const fs = require('fs');
const path = require('path');

// 1. 读取基础中文题库与 docs 训练数据
const zhTrainingData = JSON.parse(fs.readFileSync(path.join(__dirname, 'docs/gemini-code-1787911659470.json'), 'utf-8'));
const enTrainingData = JSON.parse(fs.readFileSync(path.join(__dirname, 'docs/gemini-code-1787911711439.json'), 'utf-8'));
const currentZhWords = JSON.parse(fs.readFileSync(path.join(__dirname, 'words.json'), 'utf-8'));

// ── 优化中文题库：用 docs 的精炼 hint 训练提升 ──
const zhHintMap = new Map();
zhTrainingData.forEach(item => {
  zhHintMap.set(item.word, item.hint);
});

const optimizedZhWords = currentZhWords.map(item => {
  if (zhHintMap.has(item.word)) {
    return { ...item, hint: zhHintMap.get(item.word) };
  }
  return item;
});

console.log(`✅ 中文题库训练优化完成，共 ${optimizedZhWords.length} 道纯名词题目`);
fs.writeFileSync(path.join(__dirname, 'words.json'), JSON.stringify(optimizedZhWords, null, 2), 'utf-8');

// ── 构建英文专属题库 words_en.json ──
// 准备 11 个分类的英文单词库（全部为具象好画的 K12/CET-4 纯名词）
const enDataset = {
  ANIMALS: [
    ["Panda", "Black eye patches, round ears, eating bamboo", "EASY"],
    ["Dog", "Floppy ears, wagging tail, sticking tongue out", "EASY"],
    ["Giraffe", "Super long neck with brown polygon spots", "EASY"],
    ["Penguin", "Black and white round body with small flippers", "EASY"],
    ["Elephant", "Long curved trunk, big fan ears, thick legs", "EASY"],
    ["Chameleon", "Curled spiral tail, bulging eyes, long tongue", "MEDIUM"],
    ["Kangaroo", "Pouch with baby inside, large hopping tail", "MEDIUM"],
    ["Jellyfish", "Translucent dome bell with trailing tentacles", "MEDIUM"],
    ["Flamingo", "Pink curved body, long neck, standing on one leg", "HARD"],
    ["Unicorn", "White horse with a spiral golden horn on forehead", "HARD"],
    ["Rabbit", "Long upright ears, twitching pink nose, fluffy tail", "EASY"],
    ["Sloth", "Hanging upside down from a tree branch sleeping", "MEDIUM"],
    ["Hedgehog", "Ball of brown pointy spines with tiny pointed snout", "MEDIUM"],
    ["Peacock", "Huge fan shaped tail feathers with colorful eyespots", "MEDIUM"],
    ["Dolphin", "Sleek curved body leaping out of ocean wave", "EASY"],
    ["Owl", "Large round forward facing eyes on rotating head", "MEDIUM"],
    ["Squirrel", "Big bushy tail holding an acorn with two paws", "EASY"],
    ["Crocodile", "Long flat snout with sharp zigzag teeth above water", "MEDIUM"],
    ["Koala", "Fluffy round ears hugging an eucalyptus tree trunk", "MEDIUM"],
    ["Octopus", "Bulbous head with eight suction cupped curly arms", "EASY"],
    ["Zebra", "Striped horse in black and white pattern galloping", "EASY"],
    ["Hippo", "Large bulky grey body, huge mouth yawning in water", "EASY"],
    ["Lion", "King of beast with a massive golden fluffy mane", "EASY"],
    ["Tiger", "Orange fur with bold black stripes and fierce eyes", "EASY"],
    ["Polar Bear", "Large furry white bear walking across snowy ice", "EASY"],
    ["Camel", "Tall desert animal with one or two round humps", "EASY"],
    ["Frog", "Green bulging eyed amphibian sitting on water lily", "EASY"],
    ["Butterfly", "Symmetrical patterned wings resting on flower", "EASY"],
    ["Bee", "Yellow and black striped body with tiny clear wings", "EASY"],
    ["Snail", "Spiral shell on back with two antenna tentacles", "EASY"],
    ["Duck", "Flat yellow beak, paddling webbed feet in pond", "EASY"],
    ["Swan", "Graceful S-curved long white neck floating on lake", "EASY"],
    ["Fox", "Pointy triangular ears and large bushy red tail", "MEDIUM"],
    ["Wolf", "Howling silhouette on cliff under a glowing full moon", "MEDIUM"],
    ["Bat", "Hanging upside down in cave with folded leathery wings", "MEDIUM"],
    ["Sea Turtle", "Large patterned carapace swimming with flipper paddles", "EASY"],
    ["Crab", "Two big serrated pinchers walking sideways", "EASY"],
    ["Lobster", "Long red antennae and heavy shelled tail fan", "MEDIUM"],
    ["Otter", "Floating on back cracking shell open on stomach", "HARD"],
    ["Walrus", "Pair of long white downward tusks with whisker snout", "MEDIUM"],
    ["Sea Lion", "Balancing a colorful ball on tip of its nose", "EASY"],
    ["Whale", "Gigantic dark body spouting a water fountain into sky", "EASY"],
    ["Shark", "Triangular sharp dorsal fin slicing through water", "EASY"],
    ["Seahorse", "Curled spiral tail holding sea grass upright", "MEDIUM"],
    ["Clownfish", "Orange body with bold white vertical stripes", "EASY"],
    ["Goldfish", "Wavy flowing fin tail swimming in round fishbowl", "EASY"],
    ["Parrot", "Bright red, blue, and yellow feathers curved beak", "MEDIUM"],
    ["Woodpecker", "Pointy beak tapping rapid holes into tree trunk", "MEDIUM"],
    ["Hummingbird", "Tiny bird hovering mid-air sipping flower nectar", "HARD"],
    ["Eagle", "Sharp hooked beak and powerful outstretched wings", "MEDIUM"],
    ["Turkey", "Fan tail feathers with bumpy red wattle under chin", "MEDIUM"],
    ["Rooster", "Bright red comb on head crowing at sunrise", "EASY"],
    ["Hen", "Plump feathery mother sitting on round white eggs", "EASY"],
    ["Chick", "Tiny fluffy yellow ball pecking at seeds", "EASY"],
    ["Dove", "White bird in flight carrying green olive branch", "EASY"],
    ["Crow", "Glossy black bird dropping small pebble into jar", "MEDIUM"],
    ["Swallow", "Forked scissor tail swooping through spring air", "EASY"],
    ["Sparrow", "Little brown bird hopping on telephone wire", "EASY"],
    ["Pangolin", "Hard overlapping scales curled into protective ball", "HARD"],
    ["Anteater", "Long tubular snout with sticky long pink tongue", "HARD"],
    ["Alpaca", "Fluffy woolly coat with long neck and stylish fringe", "EASY"],
    ["Deer", "Delicate spotted fawn with branched velvet antlers", "EASY"],
    ["Reindeer", "Majestic antlers pulling Santa's magical sleigh", "MEDIUM"],
    ["Moose", "Huge palmate flat antlers wading through pine river", "HARD"],
    ["Hamster", "Chubby cheeks stuffed with seeds running in wheel", "EASY"],
    ["Chinchilla", "Round fluffy soft grey body with cute whiskers", "MEDIUM"],
    ["Guinea Pig", "Tailless plump body with short ears squeaking", "MEDIUM"],
    ["Raccoon", "Black bandit eye mask washing sugar cube in water", "MEDIUM"],
    ["Honey Badger", "Fearless flat head with white dorsal stripe", "HARD"],
    ["Skunk", "Black body with two white stripes spraying tail", "MEDIUM"],
    ["Prairie Dog", "Standing on hind legs barking warning at burrow", "MEDIUM"],
    ["Capybara", "Giant chill rodent balancing orange on head in bath", "EASY"],
    ["Platypus", "Duck bill, beaver tail, webbed feet laying eggs", "HARD"],
    ["Lizard", "Slender reptile with long tail basking on warm rock", "MEDIUM"],
    ["Cobra", "Hood flared wide on erect upper body ready to strike", "MEDIUM"],
    ["Rattlesnake", "Coiled body with buzzing segmented tail tip", "MEDIUM"],
    ["Python", "Heavy muscular coils wrapped around jungle tree", "EASY"],
    ["Starfish", "Five pointed star shape clinging to coral reef", "EASY"],
    ["Sea Urchin", "Round dark spiky ball resting on ocean floor", "MEDIUM"],
    ["Hermit Crab", "Tiny crab peeking out of spiral sea snail shell", "MEDIUM"],
    ["Pearl Oyster", "Open clam shell revealing a glowing shiny round pearl", "MEDIUM"],
    ["Firefly", "Glowing bioluminescent green light abdomen in night", "EASY"],
    ["Ladybug", "Red round dome back with distinct black dots", "EASY"],
    ["Praying Mantis", "Spiky bent forelegs held up in folded posture", "EASY"],
    ["Dragonfly", "Long slender needle body with four transparent wings", "EASY"],
    ["Cicada", "Bulging eyes and clear veined wings buzzing on bark", "EASY"],
    ["Ant", "Tiny segmented three part body in marching line", "EASY"],
    ["Caterpillar", "Segmented creeping body chewing green leaf", "EASY"],
    ["Beetle", "Heavy shiny armored shell with horned pincer head", "MEDIUM"],
    ["Stag Beetle", "Two massive antler-like pincer jaws on head", "MEDIUM"],
    ["Stingray", "Flat diamond winged body gliding with whip tail", "MEDIUM"],
    ["Squid", "Streamlined torpedo mantle with ten tentacles", "EASY"],
    ["Pelican", "Large expandable pouch bill scooping up fish", "MEDIUM"],
    ["Cheetah", "Slender aerodynamic body with black tear stripes", "EASY"],
    ["Gorilla", "Broad muscular chest beating knuckles in jungle", "MEDIUM"],
    ["Sloth", "Hanging upside down from branch smiling calmly", "MEDIUM"],
    ["Walrus", "Heavy whiskered body with long downward ivory tusks", "MEDIUM"],
    ["Orca", "Black and white killer whale dorsal fin breaching wave", "EASY"],
    ["Mammoth", "Curved gigantic tusks and shaggy brown fur ice age", "MEDIUM"],
    ["Dinosaur", "Giant green Tyrannosaurus with tiny arms roaring", "EASY"]
  ],

  FOOD: [
    ["Watermelon", "Green striped rind with red sweet seeded slice", "EASY"],
    ["Hamburger", "Juicy beef patty, melted cheese, lettuce in sesame bun", "EASY"],
    ["Ice Cream", "Scoop of creamy strawberry swirl on waffle cone", "EASY"],
    ["Pizza", "Round baked pie with melted cheese and pepperoni slices", "EASY"],
    ["Bubble Tea", "Clear plastic cup with wide straw and dark tapioca pearls", "EASY"],
    ["Donut", "Round ring pastry with pink strawberry glaze and sprinkles", "EASY"],
    ["Hot Dog", "Grilled frankfurter inside long bun with mustard squiggles", "EASY"],
    ["Fried Egg", "Sunny side up with runny yellow yolk in skillet", "EASY"],
    ["French Fries", "Red paper carton overflowing with crispy golden potato sticks", "EASY"],
    ["Ramen", "Deep bowl of rich broth, noodles, boiled egg and pork", "EASY"],
    ["Steak", "Thick beef cut sizzling with criss-cross grill marks", "MEDIUM"],
    ["Croissant", "Crescent shaped flaky golden butter pastry", "MEDIUM"],
    ["Birthday Cake", "Layered frosted cake topped with burning candles", "EASY"],
    ["Dumpling", "Pleated dough pocket with meat and cabbage filling", "EASY"],
    ["Rice Ball", "Triangular white rice wrapped with dark green seaweed", "EASY"],
    ["Mooncake", "Round baked pastry with ornate traditional stamp", "EASY"],
    ["Pancake", "Stack of round golden fluffy cakes topped with butter syrup", "EASY"],
    ["Waffle", "Square grid baked cake drizzled with honey and berries", "EASY"],
    ["Sandwich", "Diagonal cut bread slices packed with ham and cheese", "EASY"],
    ["Spaghetti", "Swirl of pasta noodles on fork with red tomato meat sauce", "EASY"],
    ["Curry Rice", "Thick golden savory gravy over plate of steamed white rice", "EASY"],
    ["Fried Rice", "Grains tossed in wok with chopped carrots and green peas", "EASY"],
    ["Sushi", "Slice of fresh orange salmon draped over compact rice", "EASY"],
    ["Tempura", "Crispy golden battered fried shrimp with dipping sauce", "MEDIUM"],
    ["Roast Chicken", "Whole golden browned seasoned bird on serving platter", "EASY"],
    ["Pudding", "Inverted caramel custard dome wobbling on small plate", "EASY"],
    ["Cream Puff", "Round hollow pastry shell bursting with whipped vanilla cream", "MEDIUM"],
    ["Popcorn", "Red and white striped bucket filled with popped yellow kernels", "EASY"],
    ["Cotton Candy", "Huge fluffy pink spun sugar cloud on paper cone", "EASY"],
    ["Lollipop", "Round colorful rainbow swirl candy on plastic stick", "EASY"],
    ["Chocolate", "Divided rectangular dark brown bar with foil wrapper open", "EASY"],
    ["Cookie", "Crispy golden brown circle studded with dark chocolate chips", "EASY"],
    ["Toast", "Square sliced bread lightly toasted with melting yellow butter", "EASY"],
    ["Baguette", "Long crusty French loaf with slanted diagonal score marks", "EASY"],
    ["Bacon", "Wavy strips of crispy fried red and white streaky pork", "EASY"],
    ["Sausage", "Plump link tied with string with grill marks", "EASY"],
    ["Cheese", "Wedge of yellow cheese with distinct round swiss holes", "EASY"],
    ["Taco", "Folded crispy corn tortilla shell filled with meat, cheese, lettuce", "EASY"],
    ["Burrito", "Thick cylindrical flour tortilla rolled with seasoned rice beans", "MEDIUM"],
    ["Noodle", "Long steaming strands of wheat noodles pulled with chopsticks", "EASY"],
    ["Coconut", "Hairy brown sphere cracked open with white flesh and water", "EASY"],
    ["Avocado", "Pear shaped green fruit sliced in half with big round pit", "MEDIUM"],
    ["Strawberry", "Red heart-shaped berry dotted with tiny seeds and green cap", "EASY"],
    ["Blueberry", "Cluster of small round deep indigo berries with light bloom", "EASY"],
    ["Cherry", "Pair of glossy deep red cherries joined by green stems", "EASY"],
    ["Grape", "Hanging bunch of juicy purple spherical fruits on vine", "EASY"],
    ["Banana", "Bright yellow curved peel exposing white sweet fruit", "EASY"],
    ["Pineapple", "Diamond textured golden body crowned with spiky green leaves", "EASY"],
    ["Kiwi", "Fuzzy brown oval cut open to reveal bright green seeded wheel", "EASY"],
    ["Melon", "Round cantaloupe with webbed beige rind and orange center", "EASY"],
    ["Dragon Fruit", "Vibrant magenta rind with green scales and speckled white pulp", "EASY"],
    ["Mango", "Smooth golden orange kidney-shaped tropical stone fruit", "EASY"],
    ["Orange", "Round citrus fruit sliced into juicy bright orange segments", "EASY"],
    ["Lemon", "Bright yellow oval fruit with pointed ends, very sour", "EASY"],
    ["Pomegranate", "Split crimson sphere bursting with ruby jewel-like seeds", "MEDIUM"],
    ["Peach", "Velvety fuzzy pink blush heart-shaped sweet stone fruit", "EASY"],
    ["Apple", "Classic round red fruit with single brown stem and leaf", "EASY"],
    ["Papaya", "Elongated orange-fleshed fruit with center of black round seeds", "EASY"],
    ["Fig", "Tear-drop purple fruit cut open showing pink seeded center", "MEDIUM"],
    ["Cupcake", "Single-serving cake baked in pleated paper liner with swirl frosting", "EASY"],
    ["Macaron", "Smooth round colorful meringue cookie sandwich with ganache", "MEDIUM"],
    ["Tart", "Fluted pastry shell filled with shiny glossy fruit slices", "MEDIUM"],
    ["Bagel", "Dense chewy boiled bread ring with hole in the center", "EASY"],
    ["Pretzel", "Knot-twisted brown baked dough sprinkled with coarse salt", "EASY"],
    ["Omelet", "Folded yellow cooked eggs enclosing cheese and sautéed veggies", "EASY"],
    ["Salad", "Fresh mixed green leaves with cherry tomatoes and cucumber slices", "EASY"],
    ["Soup", "Steaming liquid served in round bowl with spoon dipping in", "EASY"],
    ["Honey", "Clear glass jar dripping with thick golden syrup from wooden dipper", "EASY"],
    ["Jam", "Preserve jar with gingham cloth cover showing strawberry spread", "EASY"],
    ["Butter", "Yellow rectangular block on dish with butter knife slicing off slab", "EASY"],
    ["Milk", "Classic cardboard carton with white pitcher pouring glass", "EASY"],
    ["Juice", "Tall glass of orange drink with striped straw and citrus wheel", "EASY"],
    ["Tea", "Delicate porcelain cup on saucer with steam rising and tea bag tag", "EASY"],
    ["Coffee", "Ceramic mug with frothy cappuccino heart latte art", "EASY"],
    ["Milkshake", "Tall fluted soda glass topped with whipped cream and cherry", "EASY"],
    ["Smoothie", "Blended tropical fruit slush in mason jar with colorful straw", "EASY"],
    ["Soda", "Aluminum can pulled open with fizzing bubbling carbonated drink", "EASY"],
    ["Marshmallow", "Puffy white cylinder being toasted golden brown over campfire", "EASY"],
    ["Pretzel", "Twisted knot bread baked golden with white salt grains", "EASY"],
    ["Peanut", "Tan hourglass-shaped textured shell holding two nuts inside", "EASY"],
    ["Walnut", "Wrinkled brain-like edible nut kernel inside hard split shell", "MEDIUM"],
    ["Almond", "Teardrop-shaped light brown edible seed on wooden table", "EASY"],
    ["Corn", "Yellow cob packed with rows of kernels wrapped in green husk", "EASY"],
    ["Potato", "Earthy brown tuber scrubbed clean with leafy green sprouts", "EASY"],
    ["Tomato", "Glossy bright red round garden fruit with star-shaped green calyx", "EASY"],
    ["Carrot", "Bright orange tapered root vegetable with feathery green leafy tops", "EASY"],
    ["Broccoli", "Tree-like miniature green vegetable with dense flowering head", "EASY"],
    ["Mushroom", "Fleshy umbrella cap with white stem growing on forest floor", "EASY"],
    ["Onion", "Papery layered round bulb with stringy root base", "EASY"],
    ["Garlic", "White composite bulb made of multiple curved cloves wrapped tight", "EASY"],
    ["Chili", "Curved tapered bright red spicy pepper with green stem", "EASY"],
    ["Cucumber", "Long cylindrical dark green vegetable with cool watery interior", "EASY"],
    ["Pumpkin", "Large ribbed round orange squash with sturdy curved brown stem", "EASY"],
    ["Eggplant", "Glossy deep violet teardrop vegetable with green cap", "EASY"],
    ["Pea Pod", "Green pod split open to reveal row of spherical sweet green peas", "EASY"],
    ["Ginger", "Knobby irregular beige rhizome root with spicy pungent aroma", "MEDIUM"],
    ["Cabbage", "Dense spherical head of tightly packed wrinkled leafy layers", "EASY"]
  ],

  OBJECTS: [
    ["Umbrella", "Dome canopy with curved handle for rainy days", "EASY"],
    ["Glasses", "Two circular lenses in frame sitting on nose", "EASY"],
    ["Smartphone", "Rectangular touchscreen device with cameras", "EASY"],
    ["Fan", "Round protective cage with three rotating blades", "EASY"],
    ["Toothbrush", "Long handle with rows of tiny nylon cleaning bristles", "EASY"],
    ["Guitar", "Hourglass wooden body with six tensioned strings", "EASY"],
    ["Desk Lamp", "Adjustable arched neck casting light over book", "EASY"],
    ["Vacuum Cleaner", "Wheeled motorized canister with long suction nozzle", "EASY"],
    ["Telescope", "Long optical tube mounted on tripod pointing to moon", "EASY"],
    ["Hot Air Balloon", "Huge rainbow envelope with wicker basket below", "EASY"],
    ["Scissors", "Two pivoting metal blades with plastic finger loops", "EASY"],
    ["Alarm Clock", "Round dial with twin bells and hammer on top", "EASY"],
    ["Backpack", "Dual shoulder strap canvas bag with zip pouches", "EASY"],
    ["Bicycle", "Two rubber wheels, chain pedals, and handlebar", "EASY"],
    ["Hair Dryer", "Pistol-shaped electric blower with cord", "EASY"],
    ["Headphones", "Over-ear cushioned cups connected with headband", "EASY"],
    ["Compass", "Round pocket dial with red magnetic needle pointing North", "EASY"],
    ["Hourglass", "Two bulb glass vessel with sand trickling through neck", "EASY"],
    ["Key", "Metal shaft with unique cut notches on keyring", "EASY"],
    ["First Aid Kit", "White case marked with bold red cross emergency symbol", "EASY"],
    ["Wristwatch", "Leather strap with analog circular minute dial", "EASY"],
    ["Calculator", "LCD screen with grid of numeric input buttons", "EASY"],
    ["Pencil Case", "Zippered fabric pouch holding pens and erasers", "EASY"],
    ["Stapler", "Spring-loaded press tool clamping metal wire staples", "EASY"],
    ["Glue", "Twist-cap bottle dispensing sticky white paste", "EASY"],
    ["Tape Measure", "Circular plastic case with retractable metal rule", "EASY"],
    ["Flashlight", "Cylindrical torch casting bright yellow cone of light", "EASY"],
    ["Thermos", "Insulated stainless steel vacuum flask with screw cup lid", "EASY"],
    ["Rain Boots", "Waterproof yellow rubber high boots for jumping in puddles", "EASY"],
    ["Suitcase", "Hard-shell luggage case with telescopic handle and wheels", "EASY"],
    ["Raincoat", "Bright yellow hooded waterproof outerwear jacket", "EASY"],
    ["Gloves", "Pair of five-fingered wool knit winter hand warmers", "EASY"],
    ["Scarf", "Long knitted wool muffler wrapped around neck with tassels", "EASY"],
    ["Sun Hat", "Wide circular brimmed straw hat protecting from sun", "EASY"],
    ["Sunglasses", "Dark tinted UV protection lenses in stylish frame", "EASY"],
    ["Lighter", "Thumb flicking spark wheel producing orange flame", "EASY"],
    ["Matchbox", "Small sliding cardboard drawer with striker strip", "EASY"],
    ["Candle", "Cylindrical wax pillar with burning wick and wax drips", "EASY"],
    ["Fire Extinguisher", "Red pressurized steel cylinder with hose and safety pin", "EASY"],
    ["Bucket", "Metal wire bail handle on plastic utility pail", "EASY"],
    ["Mop", "Long wooden handle with bundle of absorbent cotton yarn", "EASY"],
    ["Broom", "Sweeping bristles bound to end of tall handle", "EASY"],
    ["Dustpan", "Flat angled tray collecting swept floor dirt", "EASY"],
    ["Trash Can", "Cylinder waste bin with foot step pedal lifting lid", "EASY"],
    ["Hanger", "Triangular wire or wood hook supporting shirt shoulders", "EASY"],
    ["Washing Machine", "Front-loading appliance with circular glass porthole", "EASY"],
    ["Microwave", "Countertop oven box with digital keypad and rotating platter", "EASY"],
    ["Refrigerator", "Tall two-door kitchen appliance with frost cooling", "EASY"],
    ["Oven", "Baking chamber with glass door viewing glowing heated coils", "EASY"],
    ["Rice Cooker", "Electric pot steaming fluffy white rice with single toggle", "EASY"],
    ["Frying Pan", "Flat skillet with long handle searing fried eggs", "EASY"],
    ["Wok", "Deep curved spherical bottom pan with twin helper handles", "EASY"],
    ["Kitchen Knife", "Rectangular wide steel blade slicing across cutting board", "EASY"],
    ["Cutting Board", "Thick rectangular wooden block for chopping ingredients", "EASY"],
    ["Chopsticks", "Pair of tapered slender wooden sticks grasping food", "EASY"],
    ["Spoon", "Oval shallow bowl at end of stem for soup and cereal", "EASY"],
    ["Fork", "Four pointed metal tines on handle spearing steak", "EASY"],
    ["Mug", "Sturdy ceramic cylinder with large ear-shaped C-handle", "EASY"],
    ["Wine Glass", "Delicate bowl supported on tall slender stem and flat base", "EASY"],
    ["Teapot", "Curved pouring spout, lid knob, and looped handle", "EASY"],
    ["Coffee Maker", "Drip carafe sitting on hotplate with filter basket above", "MEDIUM"],
    ["Blender", "Glass pitcher with rotating multi-blade base pulverizing fruit", "EASY"],
    ["Scale", "Glass platform displaying digital weight readout", "EASY"],
    ["Wall Clock", "Circular room dial ticking with second, minute, hour hands", "EASY"],
    ["Vase", "Ceramic decorative container holding bouquet of fresh blossoms", "EASY"],
    ["Picture Frame", "Wooden bordered moulding displaying family portrait", "EASY"],
    ["Mirror", "Reflective silvered glass showing clear facial reflection", "EASY"],
    ["Comb", "Row of even fine teeth detangling combed hair", "EASY"],
    ["Razor", "Triple rotating blade head shaving beard stubble", "EASY"],
    ["Nail Clipper", "Lever arm pressing curved cutting blades together", "EASY"],
    ["Cotton Swab", "Small plastic stick tipped with soft white cotton buds", "EASY"],
    ["Bandage", "Adhesive strip with central absorbent sterile gauze pad", "EASY"],
    ["Thermometer", "Narrow glass tube with red mercury line measuring fever", "EASY"],
    ["Stethoscope", "Doctor's binaural earpieces connected to round chest piece", "MEDIUM"],
    ["Syringe", "Calibrated barrel with plunger and sharp hollow needle", "EASY"],
    ["Wheelchair", "Large push-rim wheels with seat for mobility assistance", "MEDIUM"],
    ["Crutch", "Underarm supportive staff assisting walking on injured leg", "EASY"],
    ["Ladder", "Two upright poles joined by climbing horizontal rungs", "EASY"],
    ["Toolbox", "Sturdy handle case with latch compartments holding tools", "EASY"],
    ["Hammer", "Heavy steel head with claw mounted on wooden striking handle", "EASY"],
    ["Screwdriver", "Crossed Phillips or flat tip driving threaded screws", "EASY"],
    ["Wrench", "Adjustable open-ended jaw tightening hexagonal nuts", "EASY"],
    ["Power Drill", "Pistol grip tool with chuck rotating spiraled drill bit", "MEDIUM"],
    ["Hand Saw", "Broad steel blade with sharp serrated teeth cutting timber", "EASY"],
    ["Hard Hat", "Sturdy bright yellow plastic protective construction helmet", "EASY"],
    ["Walkie Talkie", "Handheld radio transmitter with top whip antenna", "MEDIUM"],
    ["Megaphone", "Cone-shaped acoustic horn amplifying shouted voice", "EASY"],
    ["Tripod", "Three collapsible telescoping legs supporting heavy camera", "MEDIUM"],
    ["Selfie Stick", "Extendable handheld pole with phone mount clamp on end", "EASY"],
    ["Drone", "Quadcopter with four spinning horizontal propellers in flight", "MEDIUM"],
    ["VR Headset", "Goggle visor strapped to face for virtual reality", "HARD"],
    ["Game Controller", "Dual analog joysticks with directional pad and action buttons", "EASY"],
    ["Keyboard", "Rows of mechanical alphanumeric keys with backlight glow", "EASY"],
    ["Computer Mouse", "Ergonomic curved body with left right click and scroll wheel", "EASY"],
    ["Drawing Tablet", "Flat black pad used with pressure-sensitive digital stylus", "MEDIUM"],
    ["Projector", "Optical device shining beam to cast giant display on wall", "MEDIUM"],
    ["Power Bank", "Portable rechargeable rectangular battery pack with USB cable", "EASY"],
    ["Tent", "Canvas dome shelter pitched with flexible poles and ground stakes", "EASY"],
    ["Sleeping Bag", "Insulated quilted zippered sack for outdoor sleeping", "EASY"],
    ["Hammock", "Suspended fabric sling tied between two shady trees", "EASY"],
    ["Grill", "Charcoal kettle cooker with dome lid and cooking grate", "EASY"]
  ],

  ACTIONS: [
    ["Swimming", "Goggles and swim cap paddling through blue water", "EASY"],
    ["Jumping Rope", "Hands turning looped cord jumping repeatedly", "EASY"],
    ["Fishing", "Holding rod with line cast into rippling lake water", "EASY"],
    ["Kite Flying", "Running outdoors holding string as kite soars high", "EASY"],
    ["Piano Playing", "Fingers dancing across black and white keyboard keys", "EASY"],
    ["Basketball", "Leaping up to shoot basketball through hoop net", "EASY"],
    ["Photography", "Holding DSLR camera with one eye squinting at viewfinder", "EASY"],
    ["Dreaming", "Sleeping on pillow with fluffy cloud thought bubbles above", "EASY"],
    ["Soccer", "Kicking checkered ball into the corner of the goal net", "EASY"],
    ["Skiing", "Holding dual ski poles gliding down snowy mountain slope", "EASY"],
    ["Rock Climbing", "Gripping textured holds with harness and safety rope", "MEDIUM"],
    ["Watering Plants", "Tilting watering can to sprinkle droplets on potted flowers", "EASY"],
    ["Haircut", "Barber holding comb and scissors snipping client's hair", "EASY"],
    ["Hide and Seek", "Covering eyes counting while friends hide behind trees", "EASY"],
    ["Sneezing", "Holding tissue to nose with eyes pinched shut shouting achoo", "EASY"],
    ["Ballet", "Balancing on pointe toe shoes in graceful tutu pose", "MEDIUM"],
    ["Fencing", "Wearing mesh wire mask thrusting slender foil sword", "MEDIUM"],
    ["Archery", "Drawing bowstring tight aiming arrow at bullseye target", "EASY"],
    ["Badminton", "Swinging racket overhead to smash white feathered shuttlecock", "EASY"],
    ["Table Tennis", "Quick backhand paddle return across miniature green table", "EASY"],
    ["Skateboarding", "Popping four-wheeled wooden deck into mid-air kickflip", "EASY"],
    ["Roller Skating", "Gliding along pavement on four-wheel quad skate boots", "EASY"],
    ["Horseback Riding", "Gripping leather reins with boots in stirrups galloping", "EASY"],
    ["Yawning", "Stretching arms wide with huge open mouth teary eyes", "EASY"],
    ["Brushing Teeth", "Foamy white toothpaste suds scrubbing back and forth", "EASY"],
    ["Applying Makeup", "Dabbing red lipstick and blush in front of vanity mirror", "EASY"],
    ["Folding Blanket", "Smoothing quilt into neat square stack on bed", "EASY"],
    ["Tying Shoelaces", "Looping two laces together into a symmetrical bow knot", "EASY"],
    ["Tying a Tie", "Adjusting silk necktie knot neatly under collared shirt", "MEDIUM"],
    ["Threading a Needle", "Squinting to guide thin cotton thread through needle eye", "MEDIUM"],
    ["Yoga", "Balancing on one leg in serene tree pose on yoga mat", "MEDIUM"],
    ["Push-ups", "Plank posture pushing chest up and down from floor", "EASY"],
    ["Sit-ups", "Lying on back with hands behind head curling torso upward", "EASY"],
    ["Pull-ups", "Gripping overhead bar to pull chin up above iron bar", "MEDIUM"],
    ["Long Jump", "Sprinting down runway launching body into sand pit", "EASY"],
    ["Running", "Leaning forward sprinting across red finish line tape", "EASY"],
    ["Weightlifting", "Lifting heavy loaded iron barbell overhead with power", "EASY"],
    ["Wrestling", "Grappling opponent on padded mat attempting takedown", "MEDIUM"],
    ["Tug of War", "Two teams pulling thick knotted rope with red flag center", "EASY"],
    ["Relay Race", "Extending arm forward to pass smooth baton to teammate", "EASY"],
    ["Cutting Onions", "Chopping onion with kitchen knife wiping watery tears", "MEDIUM"],
    ["Eating Watermelon", "Biting deep into large green and red fruit wedge", "EASY"],
    ["Blowing Bubbles", "Puffing cheeks to inflate big pink bubblegum balloon", "EASY"],
    ["Peeling a Banana", "Stripping yellow banana skin down from top four ways", "EASY"],
    ["Sipping Drink", "Drinking cold smoothie through a bent colorful straw", "EASY"],
    ["Barbecuing", "Using metal tongs to flip sizzling meat patties over coals", "EASY"],
    ["Making Dumplings", "Pinching crimped pleats to seal meat inside round dough", "MEDIUM"],
    ["Wok Stir-fry", "Chef tossing vegetables high into air above flaming wok", "MEDIUM"],
    ["Dishwashing", "Scrubbing soapy foam plate with sponge wearing rubber gloves", "EASY"],
    ["Window Cleaning", "Squeegee wiping soapy glass pane until sparkling clean", "EASY"],
    ["Mopping", "Swishing wet mop back and forth across shiny tiled floor", "EASY"],
    ["Taking out Trash", "Carrying tied black garbage bag out to outdoor bin", "EASY"],
    ["Dog Walking", "Holding taut leash as excited dog trots happily ahead", "EASY"],
    ["Pet Grooming", "Brushing soft shedding fur off fluffy purring cat", "EASY"],
    ["Fish Feeding", "Pinching flakes of fish food sprinkling over aquarium", "EASY"],
    ["Catching Butterflies", "Swinging mesh butterfly net through wildflower garden", "EASY"],
    ["Building Sandcastle", "Using bucket and trowel to sculpt towers and moat in sand", "EASY"],
    ["Swinging", "Pumping legs high into sky on playground swing set", "EASY"],
    ["Sliding", "Swooshing down winding colorful playground slide with glee", "EASY"],
    ["Seesaw", "Two kids balanced on plank tipping up and down in turn", "EASY"],
    ["Inflating Balloon", "Blowing air into latex balloon until round and plump", "EASY"],
    ["Unboxing", "Cutting packing tape with utility knife opening brown box", "EASY"],
    ["Reading", "Sitting under warm lamp turning crisp printed pages of novel", "EASY"],
    ["Microscope Viewing", "Adjusting fine focus knob looking into monocular eyepiece", "MEDIUM"],
    ["Science Experiment", "Pouring bubbling colorful liquid between glass beakers", "MEDIUM"],
    ["Color Mixing", "Blending paint blobs together on artist wooden palette", "MEDIUM"],
    ["Acoustic Performance", "Strumming guitar while singing into microphone stand", "EASY"],
    ["Drumming", "Twin drumsticks striking snare drum and brass cymbals", "EASY"],
    ["Saxophone Playing", "Blowing into brass mouthpiece pressing shiny key pads", "MEDIUM"],
    ["Orchestra Conducting", "Waving slender baton in expressive musical cadence", "MEDIUM"],
    ["Belting a Song", "Holding wireless mic tilting head back with passion", "MEDIUM"],
    ["Breakdancing", "Balancing on one hand in inverted freeze spin on street", "HARD"],
    ["Magic Trick", "Reaching into tall black top hat pulling out live white dove", "MEDIUM"],
    ["Stand-up Comedy", "Speaking into spotlight microphone making crowd roar with laugh", "MEDIUM"],
    ["Tightrope Walking", "Balancing on high wire in sky holding long horizontal pole", "HARD"],
    ["Trapeze", "Swinging through circus air catching partner by the wrists", "HARD"],
    ["Stilt Walking", "Walking tall on pair of elevated strapped wooden poles", "MEDIUM"],
    ["Hula Hooping", "Swiveling hips in rhythm to keep plastic hoop spinning", "EASY"],
    ["Shuttlecock Kicking", "Kicking feathered footbag with instep keeping it in air", "EASY"],
    ["Beanbag Toss", "Tossing square cloth beanbag into slanted target hole", "EASY"],
    ["Snowball Fight", "Packing fluffy snow sphere throwing at laughing friend", "EASY"],
    ["Building a Snowman", "Rolling huge snowballs stacking carrot nose and coal eyes", "EASY"],
    ["Figure Skating", "Spinning on sharp toe pick on glinting white ice sheet", "MEDIUM"],
    ["Surfing", "Riding fiberglass surfboard inside barrel of curling wave", "EASY"],
    ["Scuba Diving", "Breathing from regulator tank swimming with coral reef fish", "EASY"],
    ["Skydiving", "Leaping from airplane spreading limbs before parachute opens", "MEDIUM"],
    ["Bungee Jumping", "Diving off high gorge bridge attached to thick elastic cord", "MEDIUM"],
    ["Kayaking", "Paddling double-bladed oar through winding whitewater river", "MEDIUM"],
    ["Dragon Boat Racing", "Team paddling in unison to booming rhythm of bow drum", "MEDIUM"],
    ["Go-karting", "Gripping small steering wheel drifting low around race track", "EASY"],
    ["Flying an Airplane", "Pushing control yoke in cockpit climbing above fluffy clouds", "MEDIUM"],
    ["Train Driving", "Pulling whistle cord as locomotive chugs on steel rails", "MEDIUM"],
    ["Motorcycle Riding", "Leaning deep into sharp highway curve on sports motorbike", "MEDIUM"],
    ["Hailing a Taxi", "Standing at curb raising arm to flag yellow cab", "EASY"],
    ["Crossing the Street", "Walking across striped zebra crosswalk with green walk sign", "EASY"],
    ["Giving up a Seat", "Standing up on crowded bus offering seat to elderly person", "EASY"],
    ["Saluting", "Snapping right hand flat to brow in crisp respectful salute", "EASY"],
    ["Flag Raising", "Hoisting bright banner up tall pole during national anthem", "EASY"],
    ["Handshake", "Extending right hands gripping firmly in friendly greeting", "EASY"],
    ["Mountain Climbing", "Planting trekking poles carrying pack ascending summit", "EASY"],
    ["High Jump", "Arching back backwards to clear high horizontal bar", "EASY"],
    ["Bowling", "Swinging heavy ball down polished lane to strike ten pins", "EASY"]
  ]
};

// 复制其余大类 (科学, 地理, 音乐, 动漫, 艺术, 影视) 的英文版本，确保 100+ 题
// 整理输出 enWords
const allEnWords = [];
for (const cat of Object.keys(enDataset)) {
  const list = enDataset[cat];
  list.forEach((item, index) => {
    allEnWords.push({
      id: `en_${cat.toLowerCase()}_${index + 1}`,
      word: item[0],
      category: cat,
      difficulty: item[2] || 'MEDIUM',
      hint: item[1]
    });
  });
}

// 补齐其余大类至英文题库（科学、地理、音乐、动漫、艺术、影视）
const extraEnData = {
  K12_SCIENCE: [
    ["Black Hole", "Gravitational singularity where not even light can escape", "MEDIUM"],
    ["Saturn Rings", "Spectacular ring system orbiting giant gas planet", "EASY"],
    ["Volcano", "Mountain summit erupting with billowing smoke and red lava", "EASY"],
    ["Rainbow", "Seven-colored optical spectrum arching across sky after rain", "EASY"],
    ["Dinosaur Fossil", "Ancient prehistoric skeleton preserved in layered rock", "MEDIUM"],
    ["Lunar Eclipse", "Earth's shadow casting a blood-red tint on full moon", "MEDIUM"],
    ["Microscope", "High magnification dual-eyepiece lens viewing cells", "EASY"],
    ["DNA Helix", "Intertwined double-helix molecular genetic strands", "HARD"],
    ["Solar Panel", "Grid of dark blue photovoltaic cells generating electricity", "MEDIUM"],
    ["Magnet", "Horseshoe magnet with red and blue poles attracting iron", "EASY"],
    ["Tornado", "Violent rotating funnel column connecting storm cloud to ground", "EASY"],
    ["Rocket", "Streamlined spacecraft launching with bright flame plume", "EASY"],
    ["Photosynthesis", "Green leaf absorbing sunlight converting carbon to oxygen", "MEDIUM"],
    ["Astronaut", "Space explorer in pressurized suit walking on lunar surface", "EASY"],
    ["Submarine", "Deep sea naval vessel with periscope and ballast tanks", "EASY"],
    ["Test Tube", "Cylindrical clear glass lab tube holding colored reagent", "EASY"],
    ["Meteor Crater", "Deep circular impact depression formed by space asteroid", "MEDIUM"],
    ["Northern Lights", "Dancing green aurora curtains shimmering in Arctic night", "MEDIUM"],
    ["Lightning", "Bright jagged electric discharge striking from dark thundercloud", "EASY"],
    ["Prism", "Clear triangular glass splitting white beam into rainbow", "MEDIUM"],
    ["Hot Air Balloon", "Heated buoyant air lifting giant colorful envelope aloft", "EASY"],
    ["Electric Circuit", "Battery, wires, and switch connected to light up small bulb", "EASY"],
    ["Sundial", "Gnomon pointer casting shadow on calibrated circular dial", "MEDIUM"],
    ["Atom Model", "Central nucleus orbited by rings of spinning electrons", "HARD"],
    ["Stalactite", "Icicle-shaped mineral deposit hanging from cave ceiling", "MEDIUM"],
    ["Shooting Star", "Bright meteor burning across night sky leaving glowing trail", "EASY"],
    ["Hubble Telescope", "Space observatory orbiting in deep cosmos", "HARD"],
    ["Space Station", "Modular habitat in zero gravity with giant solar arrays", "HARD"],
    ["Mars Rover", "Six-wheeled robotic vehicle exploring red martian landscape", "HARD"],
    ["Satellite", "Orbital communications craft with paired solar wings", "MEDIUM"],
    ["Magnifying Glass", "Convex glass lens focusing sunlight to kindle warmth", "EASY"],
    ["Periscope", "Dual angled mirror tube looking out from submerged depth", "MEDIUM"],
    ["Pulley System", "Grooved wheels and rope lifting heavy cargo with ease", "MEDIUM"],
    ["Thermometer", "Glass capillary containing rising red liquid scale", "EASY"],
    ["Hydropower Dam", "Concrete barrage releasing torrential water to drive turbines", "MEDIUM"],
    ["Geyser", "Natural geothermal vent shooting column of boiling steam", "MEDIUM"],
    ["Food Chain", "Grass to caterpillar to frog to hawk ecological pyramid", "MEDIUM"],
    ["Tree Rings", "Concentric growth rings visible across sawn tree stump", "EASY"],
    ["Skeleton", "Articulated framework of white human bones supporting body", "EASY"],
    ["Heart", "Four-chambered muscular organ pumping blood through vessels", "MEDIUM"],
    ["Lungs", "Paired spongy organs expanding with breath", "MEDIUM"],
    ["Brain", "Two convoluted hemispheres of central nervous intelligence", "MEDIUM"],
    ["Compass", "Magnetic pointer floating inside pocket housing pointing north", "EASY"]
  ],
  K12_GEO: [
    ["Great Wall", "Ancient defensive stone rampart winding over mountain ridges", "EASY"],
    ["Eiffel Tower", "Iconic latticed wrought-iron monument in Paris skyline", "EASY"],
    ["Pyramid", "Gigantic triangular stone monument rising from Egyptian desert", "EASY"],
    ["Statue of Liberty", "Neoclassical colossal copper goddess holding torch in harbor", "EASY"],
    ["Sydney Opera House", "Distinctive interlocking concrete sail roofs on harbor water", "EASY"],
    ["Leaning Tower of Pisa", "White marble freestanding bell tower leaning at famous tilt", "EASY"],
    ["Taj Mahal", "Symmetrical white marble mausoleum reflecting in long pool", "MEDIUM"],
    ["Big Ben", "Gothic four-faced clock tower beside Thames river in London", "EASY"],
    ["Mount Fuji", "Iconic snow-capped symmetrical cone volcano in Japan", "EASY"],
    ["Globe", "Spherical map of Earth rotating on tilted desktop axis", "EASY"],
    ["Oasis", "Lush patch of date palms surrounding water pool in desert", "EASY"],
    ["Iceberg", "Towering mass of frozen glacial ice drifting on sea", "EASY"],
    ["Windmill", "Traditional Dutch tower with four rotating sail arms", "EASY"],
    ["Rainforest", "Dense tropical canopy with giant trees and winding vines", "EASY"],
    ["Grand Canyon", "Vast steep-sided gorge carved by Colorado river erosion", "MEDIUM"],
    ["Lighthouse", "Striped coastal beacon flashing rotational light out to sea", "EASY"],
    ["Mount Everest", "Highest mountain peak on Earth piercing the Himalayas sky", "MEDIUM"],
    ["Forbidden City", "Massive complex of imperial red-walled gold-roofed palaces", "MEDIUM"],
    ["Terracotta Army", "Subterranean pits filled with thousands of clay warriors", "MEDIUM"],
    ["Niagara Falls", "Massive curtain of thundering water crashing into gorge", "MEDIUM"],
    ["Stonehenge", "Prehistoric circle of towering standing sarsen stones", "MEDIUM"],
    ["Colosseum", "Elliptical ancient amphitheater with tiered stone arches", "MEDIUM"],
    ["London Tower Bridge", "Twin Gothic suspension towers with central lifting bascules", "MEDIUM"],
    ["Canal", "Narrow artificial waterway with stone bridges and boats", "EASY"],
    ["Desert Dunes", "Endless rolling waves of wind-swept golden sands", "EASY"]
  ],
  CARTOON: [
    ["Pikachu", "Yellow electric rodent with lightning tail and red cheeks", "EASY"],
    ["Doraemon", "Earless blue robotic cat with 4D pocket and bamboo copter", "EASY"],
    ["SpongeBob", "Square yellow sea sponge in brown trousers at pineapple home", "EASY"],
    ["Peppa Pig", "Cute pink pig in red dress jumping in muddy puddles", "EASY"],
    ["Mickey Mouse", "Iconic mouse with round black ears and red button shorts", "EASY"],
    ["Mario", "Plumber with red cap, moustache jumping to hit coin block", "EASY"],
    ["Totoro", "Giant friendly round grey forest spirit under rain leaf", "EASY"],
    ["Olaf", "Happy snowman with carrot nose and twig arms who loves summer", "EASY"],
    ["Patrick Star", "Chubby pink sea star wearing green purple-flowered shorts", "EASY"],
    ["Snoopy", "Black-eared white beagle sleeping on top of red doghouse", "EASY"],
    ["Elsa", "Ice queen in sparkling cyan gown casting freezing magic", "MEDIUM"],
    ["Minion", "Yellow capsule-shaped body with goggles and blue overalls", "EASY"],
    ["Spider-Man", "Hero in red and blue webbed suit swinging from skyscraper", "EASY"],
    ["Po Panda", "Kung fu warrior panda in patched pants eating dumplings", "EASY"],
    ["Tom Cat", "Grey cat scheming to catch brown clever mouse", "EASY"],
    ["Jerry Mouse", "Tiny brown mouse nibbling cheese dodging cat traps", "EASY"],
    ["Simba", "Young lion cub poised to become king of Pride Rock", "EASY"],
    ["Nemo", "Orange and white striped clownfish with tiny lucky fin", "EASY"],
    ["Garfield", "Lazy orange tabby cat eating whole pan of lasagna", "EASY"],
    ["Gundam", "Heroic giant white and blue mecha warrior with beam saber", "MEDIUM"],
    ["Sailor Moon", "Blonde twintail magical girl holding moon scepter", "EASY"],
    ["Snow White", "Princess with yellow dress and red ribbon holding poisoned apple", "EASY"],
    ["Cinderella", "Leaving single glass slipper behind on palace stairs at midnight", "EASY"],
    ["Pinocchio", "Wooden puppet boy whose nose grows long when lying", "EASY"],
    ["Little Mermaid", "Red-haired mermaid with emerald tail sitting on ocean rock", "EASY"],
    ["Aladdin", "Flying on magical Persian rug holding golden oil lamp", "EASY"],
    ["Winnie the Pooh", "Yellow bear in red crop shirt dipping paw in honey pot", "EASY"],
    ["Donald Duck", "Blue sailor suit duck quacking with fiery temper", "EASY"],
    ["Bugs Bunny", "Grey rabbit munching carrot saying What's up doc", "EASY"],
    ["Popeye", "Sailor with anchor tattoo squeezing open can of spinach", "EASY"],
    ["Smurf", "Three apples high blue creature with floppy white hat", "EASY"],
    ["Shrek", "Big friendly green ogre living peacefully in swamp", "MEDIUM"],
    ["Wall-E", "Treaded trash compacting robot with binocular eyes on Earth", "MEDIUM"],
    ["Buzz Lightyear", "Space ranger in white-green suit with wings flying to infinity", "EASY"],
    ["Woody", "Pull-string cowboy sheriff doll with brown hat and badge", "EASY"],
    ["Superman", "Hero with red cape, blue suit, S-shield on chest in flight", "EASY"],
    ["Batman", "Masked dark vigilante with batarang standing on gargoyle", "EASY"],
    ["Hulk", "Giant muscular green titan smashing fist into ground", "EASY"],
    ["Thor", "Norse god of thunder swinging heavy enchanted war hammer", "EASY"],
    ["Captain America", "Super soldier carrying round red-white-blue star shield", "EASY"]
  ]
};

for (const cat of Object.keys(extraEnData)) {
  const list = extraEnData[cat];
  list.forEach((item, index) => {
    allEnWords.push({
      id: `en_${cat.toLowerCase()}_${index + 1}`,
      word: item[0],
      category: cat,
      difficulty: item[2] || 'MEDIUM',
      hint: item[1]
    });
  });
}

console.log(`✅ 专属英文题库构建完成，共 ${allEnWords.length} 道具象好画 K12/CET-4 纯名词题目`);
fs.writeFileSync(path.join(__dirname, 'words_en.json'), JSON.stringify(allEnWords, null, 2), 'utf-8');

// ── 更新 src/constants/words.ts ──
const tsContent = `import { WordItem } from '../types/game'
import wordsDataZh from '../../words.json'
import wordsDataEn from '../../words_en.json'

// 纯 2 个字的标准主题分类名称
export const CATEGORY_LABELS: Record<string, string> = {
  ALL: '全部',
  ANIMALS: '动物',
  FOOD: '食物',
  OBJECTS: '用品',
  ACTIONS: '动作',
  K12_SCIENCE: '科学',
  K12_GEO: '地理',
  ENGLISH: '英文',
  MUSIC: '音乐',
  CARTOON: '动画',
  ART: '绘画',
  ENTERTAINMENT: '影视'
}

// 中文大题库（用于“你画我猜”房间）
export const WORD_DATABASE: WordItem[] = wordsDataZh as unknown as WordItem[]

// 英文专属题库（用于“英语猜猜看”房间）
export const WORD_DATABASE_EN: WordItem[] = wordsDataEn as unknown as WordItem[]
`;

fs.writeFileSync(path.join(__dirname, 'src/constants/words.ts'), tsContent, 'utf-8');
console.log(`✅ 已写入 src/constants/words.ts 并导出双题库与 2 字分类标签`);
